config/routes.rb
Ambgest3::Application.routes.draw do

  netzke

  scope "ambgest" do
    scope "(:locale)", :locale => /en|it/ do
      resources :patients do
        get 'index'
        member do
          get 'manage'
        end
      end

      resources :schedules do
        get 'index'
      end

      resources :receipts do
        get 'index'
        collection do
          get 'report_detail'
        end
      end

      resources :appointments do
        get 'index'
        member do
          post 'issue_receipt'
        end
        collection do
          post 'issue_receipt'
          get 'report_detail'
        end
      end

      resources :articles do
        get 'index'
      end

      resources :users do
        get 'index'
      end

      resources :app_parameters do
        get 'index'
      end

      match "(index)",          :controller => 'welcome',   :action => 'index',       :as => :index
      match "about",            :controller => 'welcome',   :action => 'about',       :as => :about
      match "contact_us",       :controller => 'welcome',   :action => 'contact_us',  :as => :contact_us
      match "whos_online",      :controller => 'welcome',   :action => 'whos_online', :as => :whos_online
      match "wip",              :controller => 'welcome',   :action => 'wip',         :as => :wip
      match "edit_current_user",:controller => 'welcome',   :action => 'edit_current_user', :as => :edit_current_user

      match "week_plan",        :controller => 'week_plan', :action => 'index',           :as => :week_plan
      match "income_analysis",  :controller => 'week_plan', :action => 'income_analysis', :as => :income_analysis
      match "analysis_pdf",     :controller => 'week_plan', :action => 'report_detail', :as => :analysis_pdf

      match "login",            :controller => 'login',     :action => 'login',       :as => :login
      match "logout",           :controller => 'login',     :action => 'logout',      :as => :logout

      match "kill_session/:id", :controller => 'users',     :action => 'kill_session',:as => :kill_session
      match "setup",            :controller => 'setup',     :action => 'index',       :as => :setup
    end
  end

end

app/helpers/week_plan_helper.rb
# encoding: utf-8

module WeekPlanHelper

  # Drag'n'drop support alias (enables to check directly the value instead of making a direct compare to the Hash value)
  #
  DRAG_N_DROP_GLOBAL_SWITCH = AGEX_FEATURES[ :enable_drag_n_drop_support ]


  # Get schedule cell special CSS style class, depending on current (processing) date.
  # curr_date : Date instance for extracting the current date
  # is_curr_app_receipt_issued : Must be true if currently processed appointment has already issued the receipt
  # is_curr_app_receipt_issued : Must be true if currently processed appointment has an issued & delivered receipt
  #
  def get_schedule_cell_style( curr_date, is_curr_app_receipt_issued = false, is_curr_app_receipt_delivered = false )
    if ( curr_date != Date.today && is_curr_app_receipt_delivered )
      'schedule-receipt-sent'
    elsif ( curr_date == Date.today && is_curr_app_receipt_delivered )
      'schedule-receipt-sent-today'
    elsif ( curr_date != Date.today && is_curr_app_receipt_issued )
      'schedule-receipt-done'
    elsif ( curr_date == Date.today && is_curr_app_receipt_issued )
      'schedule-receipt-done-today'
    elsif ( curr_date == Date.today )
      'schedule-today'
    else
      nil
    end
  end
  # ---------------------------------------------------------------------------


  # Builds up HTML table for displaying a week's schedule based on a
  # specified date (defaults to today), starting from the beginning of the
  # week.
  # Supports drag'n'drop, but only if the global switch of the framework has been
  # enabled and the currently logged-in user is allowed to modify the weekly schedule.
  #
  # curr_date : Date instance for extracting current week;
  # schedules : a collection of all the Schedule notes of the current week.
  # appointments_cache : a collection of all the Appointment instances of the current week.
  #
  def build_week_plan_table( curr_date, schedules, appointments_cache )
    sOut = "    \r\n"                               # (Add CR+LF for each table row to improve generated source readibility)

    # This will contain all the lookup tables for DOM IDs, Appointment IDs, and empty-date place-holders' IDs
    # and will be filled during the construction of the table with several arrays, one for each cross-reference needed:
    # (Only used when drag'n'drop support is enabled) 
    dom_xref_hash = {
      :drag_appointment_ids  => [],
      :drag_appointment_doms => [],
      :drag_schedule_ids  => [],
      :drag_schedule_doms => [],
      :drop_date_schedules     => [],
      :drop_date_schedule_doms => []
    }

    sOut << content_tag( :thead, table_header_for_week( curr_date ) )
    sOut << content_tag( :tbody, table_rows_for_week( curr_date, schedules, appointments_cache, dom_xref_hash ) )
    sOut << "    \r\n"                              # (Add CR+LF for each table row to improve generated source readibility)
                                                    # Ugly but working: store in the session the X-ref. tables of the drag'n'drop DOM IDs:
    current_user = LeUser.find(session[:le_user_id])
    session["#{controller_name()}_dom_xref_hash".to_sym] = dom_xref_hash if DRAG_N_DROP_GLOBAL_SWITCH && current_user && current_user.can_do(:appointments, :update)
    return sOut
  end
  # ---------------------------------------------------------------------------



  # Builds up HTML table headers for displaying a week's schedule based on a
  # specified date (defaults to today), starting from the beginning of the
  # week.
  # curr_date : Date instance for extracting the current day
  def table_header_for_week( curr_date = Date.today )
    sOut = "\r\n"                                   # (Add CR+LF for each table row to improve generated source readibility)
    dt_start = Schedule.get_week_start( curr_date )

    dt_start.step(dt_start+5, 1) { |d|
      header_text = "" << d.day.to_s << "/" << d.month.to_s << "<br/>" << h(Schedule.long_day_name( d.cwday ))
      sOut << "    #{content_tag( :th, header_text, :class => get_schedule_cell_style( d ) )}\r\n"
    }
    sOut << "    #{content_tag( :th, h(Schedule.long_day_name(7)), :class => 'schedule-notes' )}\r\n"

    return content_tag( :tr, sOut, :class => 'schedule-header' )
  end
  # ---------------------------------------------------------------------------


  # Returns the Droppable JS text to be included in a droppable DOM Id.
  #
  def get_droppable_script( droppable_dom_id )
    text = <<-END_SRC
        Droppables.add('#{droppable_dom_id}', {
          onDrop: function(dragged, dropped, event) {
            new Ajax.Request("/week_plan/move/?from=" + dragged.id + "&to=" + dropped.id, {
              asynchronous: true, evalScripts: true, method: "post",
              onFailure: function(response) {
                  alert('Server Response FAIL!');
              }
            });
            return false;
          }
        });
    END_SRC
    text
  end
  # ---------------------------------------------------------------------------

  # Returns the Draggable JS text to be included in a draggable DOM Id.
  #
  def get_draggable_script( draggable_dom_id )
    text = <<-END_SRC
        new Draggable('#{draggable_dom_id}', { revert: 'failure', scroll: window });
    END_SRC
    text
  end
  # ---------------------------------------------------------------------------

  # Returns true if the specified current_datetime is a few seconds away from current System date & time
  #
  def has_beeen_updated_recently?( update_time )
    now = Time.now.utc
    ( (! update_time.nil?) && (update_time.year == now.year) && (update_time.month == now.month) && (update_time.day == now.day) &&
      (update_time.hour == now.hour) && (update_time.min == now.min) && ((now.sec - update_time.sec).abs < 7) )
  end
  # ---------------------------------------------------------------------------

  # Returns the highlight FX JS text to be included in the specified DOM Id
  # if the specified DateTime instance has a value only a few seconds away from current DateTime.
  #
  def get_highlight_script_if_recently_updated( dom_id, update_time )
    text = <<-END_SRC
          Effect.Pulsate('#{dom_id}');
    END_SRC
    has_beeen_updated_recently?( update_time ) ? text : ''
  end
  # ---------------------------------------------------------------------------

  # Builds up a DOM ID using the prefix and a target_datetime string
  #
  def get_unique_dom_id( prefix, target_datetime )
    "#{prefix}_#{target_datetime}".gsub(/[òàèùçé^!"'£$%&?.,;:§°<>]/,'').gsub(/[\s|]/,'_').gsub(/[\\\/=]/,'-')
  end
  # ---------------------------------------------------------------------------


  # Builds a single HTML table row for displaying a single appointments line in 
  # current week's schedule, computing the week range with the same algorithm used
  # in table_header_for_week.
  #
  # Each table cell will be built with both drag'n'drop functionality (if enabled)
  # and with a link to either show or edit the cell contents - but only if the current user
  # stored in the session can actually carry out the action involved.
  #
  # curr_date : Date instance for extracting current week
  # start_time : DateTime instance representing work shift starting time
  # offset_min : Integer offset in minutes from starting time
  # schedule  : schedule instance; it can be nil if the "schedule notes slot" is assumed to be empty for this row.
  # appointments_cache : a collection of all the Appointment instances of the current week.
  # dom_xref_hash : Hash containing all the lookup tables for DOM IDs, Appointment IDs, and empty-date place-holders' IDs.
  #                The hash will be filled during the construction of the table with several arrays, one for each cross-reference needed. 
  #
  def table_row_for_week( curr_date, start_time, offset_min, schedule, appointments_cache, dom_xref_hash )
    current_user = LeUser.find(session[:le_user_id])
    curr_tot_min = start_time.hour * 60 + start_time.min + offset_min
    curr_hour_digit = curr_tot_min / 60
    curr_min_digit = curr_tot_min % 60
    sTemp = "" << start_time.year.to_s << "-" << "%02u" % start_time.month.to_s << "-" << 
            "%02u" % start_time.day.to_s << " " <<
            "%02u" % curr_hour_digit.to_s << ":" << "%02u" % curr_min_digit.to_s << ":00"
    curr_hour = DateTime.parse(sTemp)

    sOut = "\r\n"                                   # (Add CR+LF for each table row to improve generated source readibility)
    dt_start = Schedule.get_week_start( curr_date )

                                                    # -- DAY CELL SLOT: add a table cell to the row for each working day:
    dt_start.step(dt_start+5, 1) { |d|
      curr_name = ""
      curr_updated_on = nil
      curr_id = 0
      curr_is_receipt_issued = false
      s_target_datetime = Schedule.format_datetime_coordinates_for_mysql_param( d, curr_hour )

      for app in appointments_cache
        if s_target_datetime == Schedule.format_datetime_for_mysql_param( app.date_schedule )
          curr_name = app.get_full_name
          curr_id = app.id
          curr_updated_on = app.updated_on
          curr_is_payed = app.is_payed?
          curr_is_receipt_issued = app.is_receipt_issued
          curr_is_receipt_delivered = app.is_receipt_delivered
          break
        end
      end
                                                    # Build-up basic link to insert into the cell:
      table_data = ( curr_is_payed ? content_tag(:div, '', :class => 'schedule-payed-img') : '' ) +
                   link_to_unless(
                            ( current_user.nil? ||
                              !( curr_name.blank? ? current_user.can_do(:appointments, :create) :
                                                    current_user.can_do(:appointments, :show)
                               )
                            ),
                            "%02u" % curr_hour_digit.to_s << ":" << "%02u" % curr_min_digit.to_s,

app/views/week_plan/income_analysis.html.erb
<script type="text/javascript" >
	Ext.onReady(
		function() {
			Ext.create( 'Ext.Container', {
				renderTo: Ext.get('agex_top_actions'),
				layout : {
					type: 'hbox',
					maxHeight: 30
				},
				items : [
					<%= create_extjs_button_config(
						:analysis_pdf,
						:income_analysis,
						analysis_pdf_path( :date_schedule => @date_schedule ),
						'page_white_acrobat.png'
					) %>
				]
			});
		}		
	);
</script>


<p/>
<br/>
<p/>

<h2><%= "#{I18n.t(:time_invoicing_title, :scope =>[:invoice_row])}" %></h2>

<%= netzke :invoice_analysis_filter_panel, {
    :class_name => "InvoicesAnalysisFilteringPanel",
	:filtering_date_start => @filtering_date_start,
	:filtering_date_end   => @filtering_date_end,
	:override_filtering	  => @override_filtering,
	:show_current_user_firm => true,
	:view_config => {
		:force_fit => true # force the columns to occupy all the available width
	}
} %>
<br/>

<div id='div_invocing_by_week_chart'></div>

<p/>
<br/>
<br/>
<p/>


<h2><%= I18n.t(:receipts_list_during_period, {:scope=>[:income_analysis]}) %>:&nbsp;<%= h( @filters_status ) %></h2>

<div id='agex_top_actions'></div>

<!-- Receipts / income summary: -->
<table class="income-analysis">
  <tbody>

  <tr>
    <th><%= I18n.t(:receipt, 				{:scope=>[:income_analysis]}) %></th>
    <th><%= I18n.t(:base_amount, 			{:scope=>[:income_analysis]}) %> (€)</th>
    <th><%= I18n.t(:items_to_be_divested, 	{:scope=>[:income_analysis]}) %></th>
    <th><%= I18n.t(:net_taxable, 			{:scope=>[:income_analysis]}) %> (€)</th>
    <th><%= I18n.t(:entries_percentage,		{:scope=>[:income_analysis]}) %> (€)</th>
    <th><%= I18n.t(:tot_additional_charges, {:scope=>[:income_analysis]}) %></th>
    <th><%= I18n.t(:gross_amount, 			{:scope=>[:income_analysis]}) %> (€)</th>
    <th><%= I18n.t(:receipt_delivered,		{:scope=>[:income_analysis]}) %></th>
    <th><%= I18n.t(:is_payed, 				{:scope=>[:income_analysis]}) %></th>
  </tr>

  <% grand_total = tot_to_be_payed = tot_base_price = tot_minus_costs = tot_plus_costs = tot_percentages = tot_net_price = tot_payed = 0.0 %>
  <% tot_is_delivered = tot_is_payed = 0 %>


  <% for receipt in @receipts_per_week %>
    <tr class="<%= cycle('odd', 'even') %>">
      <% costs = receipt.get_additional_cost_totals %>
      <% net_price = receipt.net_price %>
      <% percentage_amount = receipt.account_percentage_amount %>

      <% tot_base_price += receipt.price %>
      <% tot_minus_costs += costs[:negative] %>
      <% tot_plus_costs += costs[:positive] %>
      <% tot_percentages += percentage_amount %>
      <% tot_net_price += net_price %>
      <% amount = net_price + percentage_amount + costs[:positive] - costs[:negative] %>
      <% receipt.is_payed? ? tot_payed += receipt.price.to_f : tot_to_be_payed += receipt.price.to_f %>
      <% tot_is_delivered += 1 if receipt.is_receipt_delivered? %>
      <% tot_is_payed     += 1 if receipt.is_payed? %>

      <td align="left">
      	<% if receipt.is_payed? %>
      		<b><%= h(receipt.get_receipt_header) %></b>
      	<% else %>
     		<%= h(receipt.get_receipt_header) %>
      	<% end %>
      </td>
      <td align="right"><%= h( "%6.2f" % receipt.price.to_s ) %></td>
      <td align="right"><%= h( "%6.2f" % costs[:negative].to_s ) %></td>
      <td align="right"><%= h( "%6.2f" % net_price.to_s ) %></td>
      <td align="right"><%= h( "%6.2f" % percentage_amount.to_s ) %></td>
      <td align="right"><%= h( "%6.2f" % costs[:positive].to_s ) %></td>
      <td align="right">
      	<% if receipt.is_payed? %>
	      	<b><%= h( "%6.2f" % amount.to_s ) %></b>
      	<% else %>
	      	<%= h( "%6.2f" % amount.to_s ) %>
      	<% end %>
      </td>
      <td align="center"><%= show_chkbox( receipt.is_receipt_delivered? ) %></td>
      <td align="center"><%= show_chkbox( receipt.is_payed? ) %></td>
    </tr>


	<!-- Appointments sub-table: -->
	<% unless ( @appointments_per_receipt[ receipt.id ].nil? || @appointments_per_receipt[ receipt.id ].size < 1 ) %>
		<tr class="<%= cycle('odd-smaller', 'even-smaller') %>">
			<td></td>
			<td align="center"><i><%= I18n.t(:invoiced_appointments, 	{:scope=>[:income_analysis]}) %>:</i></td>
			<td></td>
			<td></td>
			<td align="center"><i><%= I18n.t(:patient__get_full_name, 	{:scope=>[:appointment]}) %></i></td>
			<td align="center"><i><%= I18n.t(:appointment, 	{:scope=>[:appointment]}) %></i></td>
			<td align="center"><i><%= I18n.t(:price, 	{:scope=>[:appointment]}) %></i></td>
			<td></td>
			<td align="center"><i><%= I18n.t(:is_payed, 	{:scope=>[:appointment]}) %></i></td>
		</tr>
		<% tot_count = 0 %>
		<% tot_appointments_payed = tot_appointments_amount = 0.0 %>
		<% for appointment in @appointments_per_receipt[ receipt.id ] %>
			<tr class="<%= cycle('odd-smaller', 'even-smaller') %>">
				<% tot_count += 1 %>
				<% tot_appointments_amount += appointment.price.to_f %>
				<% tot_appointments_payed += appointment.price.to_f if appointment.is_payed? %>
				<% appointment_verbose = appointment.get_verbose_name.split(' @ ') %>

				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td align="center"><%= h( appointment_verbose[0] ) %></td>
				<td align="center"><%= h( appointment_verbose[1] ) %></td>
				<td align="right"><%= h( "%6.2f" % appointment.price ) %></td>
				<td></td>
				<td align="center"><%= show_chkbox( appointment.is_payed? ) %></td>
			</tr>
		<% end %>
		<tr class="analysis-subsummary">
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
    		<td align="center"><%= I18n.t(:subtotals, {:scope=>[:income_analysis]}) %>:</td>
			<td align="right"><%= h( "%6.2f" % tot_appointments_amount ) %></td>
			<td align="right"><%= I18n.t(:to_be_payed, {:scope=>[:receipt]}) %>:<br/><%= h( "%6.2f" % (tot_appointments_amount - tot_appointments_payed) ) %> €</td>
			<td align="right"<b><%= I18n.t(:payed, {:scope=>[:receipt]}) %>:<br/><%= h( "%6.2f" % tot_appointments_payed ) %> €</b></td>
		</tr>
	  <% end %>

	  <tr class="analysis-subsummary">
	    <td colspan="9"><hr/></td>
	  </tr>
  <% end %>


  <% grand_total = tot_net_price + tot_percentages + tot_plus_costs - tot_minus_costs %>
  <tr class="analysis-summary">
    <td align="center"><%= I18n.t(:totals, {:scope=>[:income_analysis]}) %>: (<%= "#{@receipts_per_week.count} " << I18n.t(:receipts, {:scope=>[:income_analysis]}) %>)</td>
    <td align="right"><%= h( "%6.2f" % tot_base_price.to_s ) %></td>
    <td align="right"><%= h( "%6.2f" % tot_minus_costs.to_s ) %></td>
    <td align="right"><%= h( "%6.2f" % tot_net_price.to_s ) %></td>
    <td align="right"><%= h( "%6.2f" % tot_percentages.to_s ) %></td>
    <td align="right"><%= h( "%6.2f" % tot_plus_costs.to_s ) %></td>
    <td align="right"><b><%= h( "%6.2f" % grand_total.to_s ) %></b></td>
    <td align="center"><%= h( "%3d" % tot_is_delivered ) %> / <%= h( "%3d" % @receipts_per_week.count ) %></td>
    <td align="center"><%= h( "%3d" % tot_is_payed ) %> / <%= h( "%3d" % @receipts_per_week.count ) %></td>
  </tr>
  <tr class="analysis-summary">
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td align="right"><%= I18n.t(:to_be_payed, {:scope=>[:receipt]}) %>:<br/><%= h( "%6.2f" % tot_to_be_payed ) %> €</td>
	<td align="right"<b><%= I18n.t(:payed, {:scope=>[:receipt]}) %>:<br/><%= h( "%6.2f" % tot_payed ) %> €</b></td>
  </tr>
  <tr class="analysis-summary">
    <td colspan="9"><hr/></td>
  </tr>

  </tbody>
</table>

<br/>

app/views/week_plan/index.html.erb
<div id='agex_top_actions'></div>


<%= netzke :weekly_planner_panel, {
	:class_name => "WeekPlannerPanel",
	:width => "98%",
	:height => 1763
} %>


<div id="divIssueReceiptDataContainer" hidden="true">
	<%= form_tag( issue_receipt_appointments_path(), :id => 'frmPostIssueReceipt' ) do -%>
		<%= hidden_field_tag( :data ) %>
	<% end %>
</div>